name: Deploy Wiki

on:
  push:
    paths:
      - 'kubernetes/docs/**'
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install rsync
      id: install_rsync
      run: |
        sudo apt install rsync grsync
    - name: Clone Wiki
      id: clone_wiki
      run: |
        git config --global --add safe.directory "/github/workspace"
        git config --global --add safe.directory "/github/workspace/wiki"
        git clone https://github.com/kubernetes-client/python.wiki.git wiki
        echo "message=$(git log -1 --format=%B)" >> $GITHUB_OUTPUT
    - name: Copy to wiki repository
      id: copy_to_wiki
      run: |
        rsync -av --delete kubernetes/docs/ wiki/ --exclude .git
    - name: Push wiki
      id: push_wiki
      run: |
        cd wiki
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "${{ steps.clone_wiki.outputs.message }}"
        git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        
